### ISSUE TITLE
TH10AI文件中DllInject遭遇死锁

### ISSUE THREAD

**Issue by chuchong** [deepmaid/Th10Ai#3]
作者您好，我用VS2017打开项目后,在32位debug模式下，在运行Th10Ai时遭遇死锁问题（已授予管理员权限），具体而言是DllInject.cpp66行。能请问您是在什么开发模式下进行的呢？

非常感谢您！

**Comment by chuchong** [comment]
原来是要先打开游戏，再启动程序，不过有游戏卡死的现象

**Comment by chuchong** [comment]
应该是在DLLInject.cpp 的 69行调用LoadLibrary时发生了死锁

**Comment by projMiss** [comment]
debug/release一直都没死锁过
66行的话，就是LoadLibrary没返回，参数dllname是什么

**Comment by projMiss** [comment]
我想起来了，VS2017的std::thread会在DllMain里死锁，导致LoadLibrary没返回。
改用boost::thread吧。

**Comment by chuchong** [comment]
多谢！验证修改了HookLoader中的thread问题解决
